### ISSUE TITLE
Could use @InjectView or @FindView on Activity?

### ISSUE THREAD

**Issue by ppamorim** [pedrovgs/EffectiveAndroidUI#11]
I can't use this annotations on activity?

**Comment by pedrovgs** [comment]
Of course you can. Review ButterKnife library documentation: https://github.com/JakeWharton/butterknife

**Comment by pedrovgs** [comment]
Of course you can, review ButterKnife documentation: https://github.com/JakeWharton/butterknife

**Comment by ppamorim** [comment]
I get it:
Caused by: java.lang.IllegalStateException: Required view 'view' with ID 2131361889 for field 'View' was not found. If this view is optional add '@Optional' annotation.

**Comment by ppamorim** [comment]
@pedrovgs any idea?

**Comment by pedrovgs** [comment]
Review your layout. You've missing any ID

**Comment by ppamorim** [comment]
I do the same with "ButterKnife.findById" and it works. Non sense.
