### ISSUE TITLE
network issues

### ISSUE THREAD

**Issue by lutaseb** [pedrovgs/EffectiveAndroidUI#13]
Hi there, 
very interesting project, particularly the way you deal with the landscape/portrait stuff, it s transparent for the coder
I have a question about the network issues (event hough I know there is no actual request..)
for example in GetTvShowsInteractor class, we wait for some data received later on and then passed to the nofityTvShowsLoaded method. What if the context disappears meanwhile, like somebody killed the app, in your opinion, should'nt the  callback object be a WeakReference?

**Comment by pedrovgs** [comment]
For sure the callback should be a weak reference :) This is just a sample and I didn't care about this little details because the sample is focused on UI patterns :)

**Comment by farmazon3000** [comment]
You should definitely state it in readme `This is just a sample and I didn't care about this little details because the sample is focused on UI patterns`!
