### ISSUE TITLE
Injected empty constructor

### ISSUE THREAD

**Issue by ezebongiovi** [pedrovgs/EffectiveAndroidUI#15]
You're telling Dagger to fill MainThreadImpl dependencies when it has no dependencies.

By the way it's an interesting project!

https://github.com/pedrovgs/EffectiveAndroidUI/blob/master/app/src/main/java/com/github/pedrovgs/effectiveandroidui/executor/MainThreadImpl.java#L32

**Comment by pedrovgs** [comment]
This is the only way you have to get an instance of this class without perform the new by yourself. If you remove this injection you can't get a MainThread implementation instance without perform the new by yourself. This implementation is needed to improve the testability of the project.

You can use another patterns like a Service Locator to get the same effect. 

I hope this is the answer to your question :)
