### ISSUE TITLE
Ups! Something went wrong :(

### ISSUE THREAD

**Issue by farmazon3000** [pedrovgs/EffectiveAndroidUI#18]
I cloned the repo, build, installed and run and I'm only getting "Ups! Something went wrong :(". Is it possible to easily display something meaningful?

**Comment by pedrovgs** [comment]
@farmazon3000 the example is ready to show random errors. If you want to show always information in the main screen you can change the implementation of this [use case](https://github.com/pedrovgs/EffectiveAndroidUI/blob/master/app/src/main/java/com/github/pedrovgs/effectiveandroidui/domain/GetTvShowsInteractor.java) to return true when the method ``haveToShowError`` is invoked.

**Comment by weslly99** [comment]
Thank you @pedrovgs :)
