### ISSUE TITLE
The "presenter" could be a interface, right?

### ISSUE THREAD

**Issue by huang-qiao** [pedrovgs/EffectiveAndroidUI#21]

**Comment by huang-qiao** [comment]
Since presenter has only abstract functions, it's much more like an interface than a class for me. Is there any reason to declare presenter as class but interface?

**Comment by pedrovgs** [comment]
Hi @huang-qiao thanks for your question. 

You are right, the presenter could be implemented with an interface. If you have time, feel free to send a PR the change :)
