### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by zkpeng** [pedrovgs/EffectiveAndroidUI#25]
I have put my twitterConsumerKey and twitterConsumerSecret in fabric.properties file, but when i come to the logingactivity then click the login button, i got the error:
**com.twitter.sdk.android.core.TwitterApiException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.**
what is the problem? thanks for advance.

**Comment by pedrovgs** [comment]
Hi @zkpeng, sorry for the late response. This issue seems to be related to the Twitter SDK library and not the project it'self. I'm closing this issue, sorry.
