### ISSUE TITLE
Cannot import project Unsupported Android Gradle Version

### ISSUE THREAD

**Issue by AizazAZ** [pedrovgs/EffectiveAndroidUI#5]
![image](https://cloud.githubusercontent.com/assets/1931778/5718599/9a4bce48-9b4a-11e4-90f9-6d2b0e6b648f.png)

**Comment by pedrovgs** [comment]
I'll try to update the Gradle Android plugin version this week. Thanks!

**Comment by AizazAZ** [comment]
I have tried updating Gradle Plugin but then it throws this error 

Error:Could not find property 'processManifest' on com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated@40594b8b.

**Comment by pedrovgs** [comment]
Hi!

I've updated android gradle plugin version to 1.0.1 and downloaded Android Studio latests version and it's working fine. Can you check if you still have the same problem?

**Comment by AizazAZ** [comment]
Thanks for awesome work (Y)

**Comment by pedrovgs** [comment]
You are welcome!
