### ISSUE TITLE
Considering activity lifecycle

### ISSUE THREAD

**Issue by misrakli** [pedrovgs/EffectiveAndroidUI#6]
Hi,
first of all thank you for your work.
One think i didn't understand is how to deal with the lifecycle of the activities related to the jobexecutor as the jobs are running in a threadpool and i need the possibility to cancel a job (while navigating through activities).
Can you give an example how you would integrate for example Loaders (or is using loaders not a good approach in this architecture) or RxJava?
Another question is, when and how to cleanup references (like callback in interactor, when presenter is no more interested in interactor results).

**Comment by pedrovgs** [comment]
Hi @misrakli!

The interactors implementation I've used for this sample is really simple, you should write more code to be able to stop an interactor execution.

RxJava or Loaders are completely out of the scope of this sample, sorry. Maybe I can create another repo to talk about that.

To clear references you'll have to link your activity/fragment lifecycle with your presenter and notify the activity is going to dead and remove your listeners. For callbacks inside interactors you can use a WeakReference if you want.

**Comment by misrakli** [comment]
hi pedrovgs,

thank you for your response and i apologize for forgetting to label my issue with 'question' ..
The point with Weakreferences is a good advise. I will give it a try.

If you are looking to create a new repo for discussing the using of loaders o.a. i would be glad if you can give me a notification (maybe by linking this question with the new repo)...maybe i can participate on that, too...

**Comment by pedrovgs** [comment]
I'll think about! If your doubts have been resolved, I'm going to mark this issue as closed!
