### ISSUE TITLE
BaseFragment onInjectDependencies called on method onAttach

### ISSUE THREAD

**Issue by alexmiragall** [pedrovgs/EffectiveAndroidUI#8]
Hola Pedro:

He estado trasteando un poco el código de baseActivity y baseFragment y me parece que hay un pequeño bug cuando se restauran los fragments. 
Hay veces (cuando el activity y sus fragments son restaurados) en el que el fragment llama a onAttach antes de que el activity pase por onCreate (creo que solo se garantiza que el activity esté correctamente inicializado en el método onActivityCreated del fragment). En este caso, la clase BaseFragment llama a inject antes de que el grafo de Dagger esté correctamente inicializado provocando un NullPointerException.

Posible solución:
Llamar a injectDependencies (clase fragment que a su vez llama a inject del activity) en onActivityCreated y utilizar los objectos "injected" solo posteriormente a esta llamada.

PD: Enhorabuena por el trabajo realizado.

**Comment by alexmiragall** [comment]
Hola Pedro:

He estado trasteando un poco el código de baseActivity y baseFragment y me parece que hay un pequeño bug cuando se restauran los fragments. 
Hay veces en el que el fragment llama a onAttach antes de que el activity pase por onCreate (creo que solo se garantiza que el activity esté correctamente inicializada en el método onActivityCreated del fragment). En este caso, la clase BaseFragment llama a inject antes de que el grafo de Dagger esté correctamente inicializado provocando un NullPointerException. 

Posible solución:
Llamar a injectDependencies en onActivityCreated y utilizar las clases "injected" solo posteriormente a esta llamada.

**Comment by pedrovgs** [comment]
Puedes enviar una pull request con ese cambio si quieres. Este repositorio solo contiene un ejemplo de uso de Dagger, en aplicaciones algo más complejas habría que modificar la inicialización del fragment en lo relacionado a Dagger para evitar problemas en algunos corner cases.

Gracias!

**Comment by alexmiragall** [comment]
ok, si tengo un rato hago el push por si quieres mergearlo. Gracias ;)
